[proxy]
#fallback_server = "example.com"

[server]
bind_address = "[::]:3000"
# auto_tls = true
# domain = "example.com" # required if auto_tls is true
# tls_cert_file = "cert/fullchain.pem"
# tls_key_file = "cert/privkey.pem"

[logger]
level = 0
console_writer = true
request_logger = true
filename = "logs/misstodon.jsonl"
max_age = 7
max_backups = 10

[database]
type = "buntdb"
address = "data/data.db"
