[proxy]
#fallback_server = "example.com"

[server]
bind_address = "[::]:3000"
#url = "https://example.com"
#tls_cert_file = "cert/localhost.pem"
#tls_key_file = "cert/localhost-key.pem"

[logger]
level = 0
console_writer = true
request_logger = true
filename = "logs/misstodon.jsonl"
max_age = 7
max_backups = 10

[database]
type = "buntdb"
address = "data/data.db"
